variables:
  user:
    env: ADMIN_USERNAME
    value: "admin"
    type: string
  password:
    env: ADMIN_PASSWORD
    value: "not-set"
    type: string

services:
  webserver:
    port: 8080
    protocol: tcp
